@apiKey = AIzaSyDWKplAl5Vp43pG0j5j3vnThRJIPwv1E44
@firebaseUrl = https://identitytoolkit.googleapis.com/v1

@baseUrl = http://localhost:10000/api

@AdminEmail = tigana137@gmail.com
@AdminPassword = 12345678


###########################
# 1- As School Admin
###########################

###
# @name firebaseLogin
POST {{firebaseUrl}}/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{AdminEmail}}",
  "password": "{{AdminPassword}}",
  "returnSecureToken": true
}

###
# @name getMySchool
GET {{baseUrl}}/schools/me
Content-Type: application/json
Authorization: Bearer {{firebaseLogin.response.body.idToken}}

###
@schoolId = {{getMySchool.response.body.id}}


###
# @name createClass
POST {{baseUrl}}/schools/{{schoolId}}/classes
Content-Type: application/json
Authorization: Bearer {{firebaseLogin.response.body.idToken}}

{
  "name": "Class 1"
}

###
# @name getClassById
GET {{baseUrl}}/schools/{{schoolId}}/classes/{{createClass.response.body.data.id}}
Content-Type: application/json
Authorization: Bearer {{firebaseLogin.response.body.idToken}}


###
# @name updateClass
PUT {{baseUrl}}/schools/{{schoolId}}/classes/{{createClass.response.body.data.id}}
Content-Type: application/json
Authorization: Bearer {{firebaseLogin.response.body.idToken}}

{
  "name": "Class 1 Updated"
}


###
# @name getSchoolClasses
GET {{baseUrl}}/schools/{{schoolId}}/classrooms/
Content-Type: application/json
Authorization: Bearer {{firebaseLogin.response.body.idToken}}

###
@classId = {{getSchoolClasses.response.body.data[0].id}}

###
# @name getExamSessions
GET {{baseUrl}}/schools/{{schoolId}}/classrooms/{{classId}}/exam-sessions
Content-Type: application/json
Authorization: Bearer {{firebaseLogin.response.body.idToken}}

